# syntax=docker/dockerfile:1

FROM rust:1.93-slim-trixie

RUN apt-get update -y \
  && apt-get install -y pkg-config make g++ libssl-dev \
  && rm -rf /var/lib/apt/lists/*

RUN rustup component add clippy

WORKDIR /workspace
